In [ ]:
import pandas as pd
import numpy as np
import warnings
import os
warnings.filterwarnings("ignore")
import json
! mkdir ~/.kaggle
! cp "kaggle.json" ~/.kaggle/
! chmod 600 kaggle.json


meta_cols = ['title', 'subtitle','keyword', 'description', 'totalDownloads', 'totalViews', 'totalVotes', 'ownerUser', 'dataset_slug']
# ownerUser and dataset_slug will be used to get URL of datasets
datasets = list()

list_page = 1
while True:
    print(f'Page {list_page} started....')
    dataset_list = ! kaggle datasets list --sort-by updated -p $list_page
    dataset_list = dataset_list[3:]
    for dataset in dataset_list:
        tmp_title = dataset.split('  ')[0]
        ! kaggle datasets metadata $tmp_title
        metadata_json = open('dataset-metadata.json', 'r')
        metadata_json = json.load(metadata_json)
        title = metadata_json['title']
        subtitle = metadata_json['subtitle']
        keywords = metadata_json['keywords']
        description = metadata_json['description']
        totalDownloads = metadata_json['totalDownloads']
        totalVotes = metadata_json['totalVotes']
        totalViews = metadata_json['totalViews']
        ownerUser = metadata_json['ownerUser']
        dataset_slug = metadata_json['datasetSlug']
        tmp_meta = [title, subtitle, keywords, description, totalDownloads, totalViews, totalVotes, ownerUser, dataset_slug]
        datasets.append(tmp_meta)
    if list_page % 5 == 0:
        datasets_df = pd.DataFrame(datasets, columns = meta_cols)
        datasets_df.to_csv(f'kaggle_dataset_df_page{list_page}.csv', index=False)
        if list_page != 5:
            os.remove(f'kaggle_dataset_df_page{list_page-5}.csv')
    list_page += 1

mkdir: /Users/shibatayuuto/.kaggle: File exists
Page 1 started....
<class 'IPython.utils.text.SList'>
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
^C
User cancelled operation
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Page 2 started....
<class 'IPython.utils.text.SList'>
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json
Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.8)
Downloaded metadata to /Users/shibatayuuto/Desktop/Edinburgh Uni/Sem1/text_for_ds/CW3/dataset-metadata.json

In [2]:
import pandas as pd
dataset_df_ = pd.read_csv('kaggle_dataset_df_page10.csv')
dataset_df_

,title,subtitle,keyword,description,totalDownloads,totalViews,totalVotes,ownerUser,dataset_slug
0,Covid19 Madrid,Daily updated Covid19 deaths at Madrid. Offici...,"['public health', 'auto-updating data', 'covid...",With more than 15.000 deaths for a region of 7...,230,29736,14,jaimevalero,covid19-madrid
1,kc_house_data,NaN,[],NaN,0,0,0,fareshosny55,kc-house-data
2,"[YOLO] Sheep, colored and occluded",All images captured from drones,['retail and shopping'],NaN,2,11,0,bjosttveit,yolo-sheep-colored-and-occluded
3,hwad-tfrecords,NaN,[],NaN,0,0,0,andy2709,hwad-tfrecords
4,____tmp dataset for 1024x1660 happywhale,NaN,['online communities'],NaN,0,2,0,dschettler8845,-tmp-dataset-for-1024x1660-happywhale
...,...,...,...,...,...,...,...,...,...
195,Campus Placement,NaN,['universities and colleges'],NaN,2,8,0,sabyasachimoitra,campus-placement
196,visdrone2000,NaN,[],NaN,0,9,0,limjunhao,visdrone2000
197,MrBeast Youtube Stats & Thumbnails (Updated Da...,Daily pull of the most recent MrBeast video stats,[],NaN,12,181,7,robikscube,mrbeast-youtube-stats-daily
198,UK Power Networks Grid and Primary substations,List of Active Grid and Primary Sites and key ...,['energy'],NaN,3,103,0,yiushingpang,uk-power-networks-grid-and-primary-substations
199,Practical Statistics for Data Scientists,"Autors: Andrew Bruce, Peter C. Bruce, Peter Ge...",[],NaN,65,1059,0,bhavinmoriya,loan-csv