In [130]:
import pandas as pd
import numpy as np
from infra.helpers import curr_day, min_day, deserialize, filter_dates, Formatting

curr_formatter = Formatting()

In [131]:
edi_df = pd.read_csv("core_algorithms/ir_eval/edinburgh_research_datasets_info.csv")
kaggle_df = pd.read_csv('core_algorithms/ir_eval/kaggle_dataset_df_page500.csv', sep='\t')
paperwithcode_df = pd.read_csv('core_algorithms/ir_eval/paperwithcode_df.csv', sep='\t')
uci_df = pd.read_csv("core_algorithms/ir_eval/uci_dataset_test.csv",)

In [132]:
paperwithcode_df.rename(columns={"owner":"ownerUser"}, inplace=True)
uci_df.rename(columns={"Name":"title", "Abstract":"description", "Datapage URL":"ownerUser"}, inplace=True)
edi_df.rename(columns={"Name":"title", "URL":"ownerUser"}, inplace=True)

In [133]:
kaggle_df['Source'] = 'Kaggle'
paperwithcode_df['Source'] = 'Paper_with_code'
uci_df['Source'] = 'uci'
edi_df['Source'] = 'Edi'

In [134]:
df = pd.concat([kaggle_df, paperwithcode_df, uci_df, edi_df], axis=0)
df = df.reset_index(drop=True)

In [135]:
df.drop(['#downloads', '#votes', 'Identifier string', 'totalViews', 'totalDownloads', 'Unnamed: 0'], axis=1, inplace=True)

In [136]:
df.drop(['totalVotes', 'Dataset'], axis=1, inplace=True)

In [137]:
df.drop(['#views', 'Rank'], axis=1, inplace=True)

In [138]:
df

,Unnamed: 0.1,title,subtitle,keyword,description,ownerUser,dataset_slug,Source,date,keywords
0,0.0,The Bachelor Contestants,This dataset contains information about past s...,[],About this dataset\n&gt; <p>Creating a bracket...,yamqwe,the-bachelor-contestantse,Kaggle,NaN,NaN
1,1.0,Mineral photos,"+39,000 images of mineral stored in 15 categories",['arts and entertainment'],NaN,floriangeillon,mineral-photos,Kaggle,NaN,NaN
2,2.0,Deepwater Ports,A Dataset of the Deepwater Port Licensing Program,"['business', 'transportation', 'water transport']",About this dataset\n&gt; <p><strong>The Deepwa...,yamqwe,deepwater-portse,Kaggle,NaN,NaN
3,3.0,ubiquant_train_target,NaN,[],NaN,goweiting,ubiquant-train-target,Kaggle,NaN,NaN
4,4.0,easy_firefly_weights,NaN,[],NaN,tejaschaudhari2811,easy-firefly-weights,Kaggle,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
17582,NaN,Trypanosoma brucei EATRO1125 AnTat1.1 assemble...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/tryp...,NaN,Edi,NaN,NaN
17583,NaN,Up or down? Resolving agreement in copular sen...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/up-o...,NaN,Edi,NaN,NaN
17584,NaN,Bayer study 15791 - Mechanism of action (MoA) ...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/baye...,NaN,Edi,NaN,NaN
17585,NaN,Radio frequency-chain selection for energy and...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/radi...,NaN,Edi,NaN,NaN
17586,NaN,SMILR sequencing data and analysis related to ...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/smil...,NaN,Edi,NaN,NaN

In [139]:
df.to_csv('core_algorithms/ir_eval/Datasets_dataset.csv', sep='\t', encoding='utf-8')

In [ ]:
kaggle_df = kaggle_df.replace(np.nan, '', regex=True)

In [ ]:
count = 0
for i in kaggle_df['description']:
    if type(i) != type("he"):
        count += 1

print(count)

In [ ]:
count = 0
for i in kaggle_df['description']:
    if type(i) != type("he"):
        count += 1
        
print(count)

In [ ]:
kaggle_df['description'] = kaggle_df['description'].apply(curr_formatter.remove_markdown)

In [ ]:
edi_df

In [ ]:
kaggle_df = pd.read_csv('core_algorithms/ir_eval/kaggle_dataset_df_page500.csv', sep = '\t')

In [ ]:
paperwithcode_df = pd.read_csv('core_algorithms/ir_eval/paperwithcode_df.csv', sep = '\t')

In [ ]:
kaggle_df['description'] = kaggle_df['description'].apply(curr_formatter.remove_markdown)

In [ ]:
kaggle_df = kaggle_df.replace(np.nan, '', regex=True)

In [ ]:
kaggle_df.to_csv('core_algorithms/ir_eval/kaggle_dataset_df_page500.csv', sep='\t', encoding='utf-8')

In [125]:
df = pd.read_csv("core_algorithms/ir_eval/Datasets_dataset.csv", sep='\t')

In [140]:
df.columns

Index(['Unnamed: 0.1', 'title', 'subtitle', 'keyword', 'description',
       'ownerUser', 'dataset_slug', 'Source', 'date', 'keywords'],
      dtype='object')

In [128]:
df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'totalViews', 'totalVotes'], axis=1, inplace=True)

,title,subtitle,keyword,description,totalDownloads,ownerUser,dataset_slug,Source
0,The Bachelor Contestants,This dataset contains information about past s...,[],About this dataset\n&gt; <p>Creating a bracket...,0,yamqwe,the-bachelor-contestantse,Kaggle
1,Mineral photos,"+39,000 images of mineral stored in 15 categories",['arts and entertainment'],NaN,5,floriangeillon,mineral-photos,Kaggle
2,Deepwater Ports,A Dataset of the Deepwater Port Licensing Program,"['business', 'transportation', 'water transport']",About this dataset\n&gt; <p><strong>The Deepwa...,1,yamqwe,deepwater-portse,Kaggle
3,ubiquant_train_target,NaN,[],NaN,0,goweiting,ubiquant-train-target,Kaggle
4,easy_firefly_weights,NaN,[],NaN,0,tejaschaudhari2811,easy-firefly-weights,Kaggle
...,...,...,...,...,...,...,...,...
9493,Stanford Earthquake Dataset (STEAD),A Global Data Set of Seismic Signals for AI,"['earth science', 'geology', 'physics', 'signa...",Properties of the dataset\nSTEAD includes two ...,31,isevilla,stanford-earthquake-dataset-stead,Kaggle
9494,Asphalt Cracks,NaN,[],NaN,2,abrahamanderson,asphalt-cracks,Kaggle
9495,Maternal Health Risk Data,Predicting health risks for pregnant patients,"['healthcare', 'public health', 'health', 'reg...",Context\nData has been collected from differen...,519,csafrit2,maternal-health-risk-data,Kaggle
9496,Medical Personal Protective Equipment Images,NaN,"['medicine', 'image data', 'covid19']",Context\nCPPE - 5 (Medical Personal Protective...,3,skaarface,medical-personal-protective-equipment-images,Kaggle
9497,Higher Education Students Performance Evaluation,Machine Learning Prediction Analysis,"['research', 'education', 'multiclass classifi...",Abstract\nThe data was collected from the Facu...,1357,csafrit2,higher-education-students-performance-evaluation,Kaggle

In [141]:
df.drop(['Unnamed: 0.1'], axis=1, inplace=True)

In [142]:
df.to_csv('core_algorithms/ir_eval/Datasets_dataset.csv', sep='\t', encoding='utf-8')

In [143]:
df = pd.read_csv("core_algorithms/ir_eval/Datasets_dataset.csv", sep='\t')

,Unnamed: 0,title,subtitle,keyword,description,ownerUser,dataset_slug,Source,date,keywords
0,0,The Bachelor Contestants,This dataset contains information about past s...,[],About this dataset\n&gt; <p>Creating a bracket...,yamqwe,the-bachelor-contestantse,Kaggle,NaN,NaN
1,1,Mineral photos,"+39,000 images of mineral stored in 15 categories",['arts and entertainment'],NaN,floriangeillon,mineral-photos,Kaggle,NaN,NaN
2,2,Deepwater Ports,A Dataset of the Deepwater Port Licensing Program,"['business', 'transportation', 'water transport']",About this dataset\n&gt; <p><strong>The Deepwa...,yamqwe,deepwater-portse,Kaggle,NaN,NaN
3,3,ubiquant_train_target,NaN,[],NaN,goweiting,ubiquant-train-target,Kaggle,NaN,NaN
4,4,easy_firefly_weights,NaN,[],NaN,tejaschaudhari2811,easy-firefly-weights,Kaggle,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
17582,17582,Trypanosoma brucei EATRO1125 AnTat1.1 assemble...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/tryp...,NaN,Edi,NaN,NaN
17583,17583,Up or down? Resolving agreement in copular sen...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/up-o...,NaN,Edi,NaN,NaN
17584,17584,Bayer study 15791 - Mechanism of action (MoA) ...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/baye...,NaN,Edi,NaN,NaN
17585,17585,Radio frequency-chain selection for energy and...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/radi...,NaN,Edi,NaN,NaN
17586,17586,SMILR sequencing data and analysis related to ...,NaN,NaN,NaN,https://www.research.ed.ac.uk/en/datasets/smil...,NaN,Edi,NaN,NaN

In [ ]:
df = pd.read_csv("core_algorithms/ir_eval/Datasets_dataset.csv", sep='\t')